# Generated by Django 3.1.1 on 2020-10-03 11:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('Image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('Image3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Product_tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_id', models.IntegerField(default=0)),
                ('tile_name', models.CharField(default='no name', max_length=200)),
                ('tile_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('tile_dimensions', models.CharField(default='no dimensions', max_length=100)),
                ('tile_application', models.CharField(default='no application', max_length=100)),
                ('tile_pattern', models.CharField(default='no pattern', max_length=100)),
                ('tile_color', models.CharField(default='no colour', max_length=100)),
                ('tile_texture', models.CharField(default='no texture', max_length=100)),
            ],
        ),
    ]
